# Generated by Django 3.1.7 on 2021-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='id',
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
