version: "3.9"

services:
  base:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  django:
    restart: always
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./docker/postgres/data/data/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "8000:8000"
    depends_on:
      - base
